on: [push, pull_request]
jobs:
  job_id:
    steps: 
      - run: echo Hello World
    runs-on: ${{matrix.platform}}
    strategy:
      matrix:
        platform: [macos-latest,windows-latest,ubuntu-latest]
